### DISCUSSION TITLE
Proxy LoadBalancer service stuck on pending and Proxy is not reachable

### DISCUSSION THREAD

**Discussion by PrexorJustin** [jeremylvln/Shulker#518] [Q&A] [answered]
I've done everything according to the Documentation but i cant seem to get this fixed

**Comment by jeremylvln** [comment]
Hi @PrexorJustin!

Shulker is only in charge of creating the `Service` resource (or `LoadBalancer` type), and not making it functional. This is left to your Cloud Provider (if you are using a SaaS like AWS or GCP) or to yourself if you are doing it on Bare Metal.

Thanks!

**Reply by PrexorJustin** [reply]
Hi! 
Thanks for replying I'm hosting a VPS on contabo do you have any guide or suggestion on how to make this functional I've tried googling myself to see how to make load balancing provision possible or functional but I've had no luck 😅

**Reply by jeremylvln** [reply, marked as answer]
If you don't mind about the port, you could use a `NodePort` service instead that will mount a port from the range Kubernetes is configured to use (something near 30000-32000):

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: proxy
spec:
  service:
    type: NodePort
    externalTrafficPolicy: Local
  # ...
```

Using a `LoadBalancer` Service is useful when you have multiple nodes and need custom network configuration to route the traffic properly. If you are using a simple setup with a VPS, there are no need for this complexity.

Get back to me :)
