### DISCUSSION TITLE
World persistence via persistent volume (claim)

### DISCUSSION THREAD

**Discussion by stevefan1999-personal** [jeremylvln/Shulker#520] [Ideas]
Extended from #519, I think we need to have a way to persist the world, otherwise it will be reset every time we restart it. This would help my project to bring minecraft server to the masses just like realm but at a cheaper price XD.

However, this can be worked around by setting custom data path:
```
      podOverrides:
        volumes:
        - emptyDir: {}
          name: server-data1
        volumeMounts:
          - mountPath: /data1
            name: server-data1
```

**Comment by jeremylvln** [comment]
Hi @stevefan1999-personal!

I just replied to #519. That was the thing I had in mind. Unfortunately, it's not that simple because server operators can choose to have a different name for the world folder (`world`) or even have multiple worlds at the root of the server folder. This makes it very difficult to have a "generic way" of putting all the worlds in one place, so one can mount this folder and persist the world.

I'll try to find a solution.

Thanks!

**Reply by risograph** [reply]
This is a feature that would seriously benefit the project. I too am using Shulker for hosting a Survival Minecraft Server where I don't want my world to be reset whenever something goes wrong. This also goes for playerdata.

**Comment by risograph** [comment]
Where did you apply this override? I tried this on my own server but I couldn't get it working, oddly.

**Comment by jroberts235** [comment]
Is it possible to modify the `spigot-config.yml` to do this? 
```
  spigot-config.yml: |+
    settings:
      bungeecord: false
      restart-on-crash: false
    advancements:
      disable-saving: false
    players:
      disable-saving: false
    stats:
      disable-saving: false
```
A patch maybe?  I'm trying to figure out what a patch actually looks like to test this but no luck so far.

Can it be done with Environment Vars?
