### DISCUSSION TITLE
Editing server.properties

### DISCUSSION THREAD

**Discussion by risograph** [jeremylvln/Shulker#528] [Q&A] [answered]
Hello! I am wondering how one would go about editing the server.properties in a pod based on a persistent file? This also goes for spigot.yml, ops.json, whitelist.json, and the other player-management JSONs that need to stay persistent. I understand this was planned information for the docs (per discussion #435's 2 and 3), but if someone else has an answer, I'd like to know. Thank you in advance!

**Comment by samuelh2005** [comment, marked as answer]
For files other then the `server.properties` you should [add patches](https://shulker.jeremylvln.fr/latest/guide/recipes/adding-custom-content.html#adding-patches). A patch is just a `tar.gz` archive with all the files you want to override (folders included). The patches would get applied to the server's root.

For editing the `server.properties`, this needs to be done via the YAML that you apply (see example YAML).

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: lobby
spec:
  clusterRef:
    name: lobby
  replicas: 1
  template:
    spec:
      clusterRef:
        name: lobby
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.20.2'
      config:
        serverProperties: # <- all the settings you put inside the `serverProperties` key will be passed to the actual `server.properties` file
          difficulty: peaceful # <- example: setting the default difficulty to peaceful.
          enable-command-block: true
```

You do need to recreate you pods for the changes to take affect.

If you want to know more available YAML values then you can check https://github.com/jeremylvln/Shulker/blob/main/packages/shulker-crds/src/v1alpha1/minecraft_server.rs.
