### DISCUSSION TITLE
Possible to Override GameServer Health Settings?

### DISCUSSION THREAD

**Discussion by jroberts235** [jeremylvln/Shulker#529] [General]
After installing a few plugins, startup is now taking long enough to fail health checks more than 5 times which triggers k8s to send a SIGHUP to the pod. We need to override these `GameServer` health attrs: 
```
  health:
    disabled: false
    periodSeconds: 15
    failureThreshold: 5
    initialDelaySeconds: 30
```
From what I can tell, this currently is not possible but I think this is something that people are going to need to do.
