### DISCUSSION TITLE
Select minecraftserver image

### DISCUSSION THREAD

**Discussion by DiogoMurano** [jeremylvln/Shulker#614] [Q&A] [answered]
Currently the itzg/minecraft-server:2024.2.1-java17 image is hardcoded, while in more recent versions of spigot, the use of java 21 is mandatory.

**Comment by jeremylvln** [comment]
Hi @DiogoMurano,

You are perfectly right. The image should be _overridable_. It's something that is planned, until then, I've bumped both images to use the latest available at time of writing, both of them targeting Java 21.

Do not hesitate if you encounter any issue using Shulker, and sorry for this late response.

**Comment by HookWoods** [comment, marked as answer]
Isn't this already a feature with podOverrides ?
https://github.com/jeremylvln/Shulker/blob/main/kube/helm/templates/crds/shulkermc.io_minecraftservers.yaml#L794


Like this:
```yaml
spec:
  clusterRef:
    name: getting-started
  replicas: 1
  template:
    spec:
      podOverrides:
        image:
          name: itzg/minecraft-server:2024.2.1-java21
```
