### DISCUSSION TITLE
Ability to choose a Java version.

### DISCUSSION THREAD

**Discussion by samuelh2005** [jeremylvln/Shulker#617] [Ideas]
Some Minecraft versions (or plugins) may require a specific Java version to run (for example Minestom or 1.20.6+ requires Java 21).

This can be achieved by installing [SDKMAN](https://sdkman.io/) inside proxy and server pods.  SDKMAN can be used to install [various JDKs](https://sdkman.io/jdks).

The example YAML shows how one may configure their Java JDK.

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet # or MinecraftServerFleet
metadata:
  name: public
spec:
  clusterRef:
    name: getting-started
  replicas: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  template:
    spec:
      javaVersion: 22.0.2-oracle # whatever gets put here will be passed to `sdk install java <version>`
      version:
        channel: Velocity # or Paper
        name: latest
```
