### DISCUSSION TITLE
How do I specify a provided Redis with TLS?

### DISCUSSION THREAD

**Discussion by kanya-approve** [jeremylvln/Shulker#912] [Q&A] [answered]
```
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: minecraft-cluster
  namespace: apps
spec:
  networkAdmins:
    - REDACTED
  redis:
    provided:
      credentialsSecretName: redis-credentials
      host: rediss://REDACTED
      port: 6379
    type: Provided
```

I don't think this is working. Does shulker lack support for tls redis?
