### ISSUE TITLE
Volumes do not get mounted

### ISSUE THREAD

**Issue by TropicLegend** [jeremylvln/Shulker#251]
### What happened?

Volumes mentioned in the  podOverrides section do not get mounted.
The config I used looks like this:
```
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: ca-server
  namespace: minecraft-network
spec:
  clusterRef:
    name: fl-net
  replicas: 1
  template:
    spec:
      podOverrides:
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "4000m"
        containers:
          volumeMounts:
            - name: ca-world
              mountPath: /data/world
            - name: ca-world-nether
              mountPath: /data/world_nether
            - name: ca-world-the-end
              mountPath: /data/world_the_end
        volumes:
          -  name: ca-world
             persistentVolumeClaim:
             claimName: ca-world-claim
          -  name: ca-world-nether
             persistentVolumeClaim:
             claimName: ca-world-nether-claim
          -  name: ca-world-the-end
             persistentVolumeClaim:
             claimName: ca-world-the-end-claim
      clusterRef:
        name: fl-net
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.20.2'
      config:
        plugins:
          - url: https://xxxxxxxxxx/s/fCn6TWGQfaHcMnz/download/EssentialsX-2.20.1.jar
          - url: https://xxxxxxxxxx/s/HjdfDzpgGAjRw9r/download/Chunky-1.3.92.jar
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-world-claim
  namespace: minecraft-network
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-world-nether-claim
  namespace: minecraft-network
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-world-the-end-claim
  namespace: minecraft-network
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
```

### Version

v0.3.0

### Kubernetes Version

1.24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
