### ISSUE TITLE
Implement lifecycle strategies on servers to automatically manage Agones allocations

### ISSUE THREAD

**Issue by jeremylvln** [jeremylvln/Shulker#355]
### Discussed in https://github.com/jeremylvln/Shulker/discussions/354

<div type='discussions-op-text'>

<sup>Originally posted by **Pyjou** January 22, 2024</sup>
I have a big question about the upgrading of a server with Shulker.

In my case, let's say I want to upgrade a plugin on one of my server fleets (proxy or not). I change the value of my url in env vars, which will be downloaded when my server starts up, and send it to kube. But we agree that kube will automatically kill all servers to apply the change, and automatically kick players. That's not what we'd generally want.

Do you think there would be a mechanism to wait until the end of a game session (like in a mini-game) before launching the upgrade? Or simply not lauchn the upgrade on servers already running and simply apply it to new servers?

What do you think about this subject?
</div>

---

The idea is to introduce a new field on the CRD named `lifecycleStrategy` which could be:
- `AllocateWhenNotEmpty` (default): the Agent plugin will ask Agones to set the server to `Allocated` when at least one player is connected on the server. When updating a server or a fleet, all the players will need to disconnect or the server will need to be manually stopped so the server can be updated
- `Manual`: the Agent plugin will only set the server as `Ready` when the agent is loaded (current behavior). It is let to any custom implementation to manage allocation and release

Example:
```yaml
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: dropper-game
spec:
  clusterRef:
    name: getting-started
  replicas: 1
  template:
    spec:
      clusterRef:
        name: getting-started
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.18.2'
      config:
        lifecycleStrategy: AllocateWhenNotEmpty # Default
        # lifecycleStrategy: Manual
```
