### ISSUE TITLE
Config escaping "<" in velocity motd

### ISSUE THREAD

**Issue by TropicalShadow** [jeremylvln/Shulker#382]
### What happened?

# Summary
The configuration process is unexpectedly adding a double backslash before the '<' character when setting values for MOTD. This behavior is not in line with the expected functionality of MiniMessage formatting.

## Proxy.yaml
set using `kubectl apply -f proxy.yaml -n bridgesplash`
```yaml
metadata:
  name: public
spec:
  clusterRef:
    name: bridgesplash
  replicas: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config:
        motd: "<red>▓▒░             ⚡</red>   <gradient:red:blue><bold>BridgeSplash</bold></gradient>   <red>⚡             ░▒▓</red>
```

## velocity.toml
Inside Velocity pod filesystem.
```toml
config-version = "2.6"
bind = "0.0.0.0:25577"
# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Only MiniMessage format is accepted.
motd = "\\<red>▓▒░             ⚡\\</red>   \\<gradient:red:blue>\\<bold>BridgeSplash\\</bold>\\</gradient>   \\<red>⚡               ░▒▓\\</red>"
show-max-players = 1500
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = true
forwarding-secret-file = "/mnt/shulker/forwarding-secret/key"
player-info-forwarding-mode = "modern"
forced-hosts = {}

[servers]
        lobby = "localhost:30000"
        try = ["lobby", "limbo"]
        limbo = "localhost:30001"
[advanced]
        tcp-fast-open = true
        haproxy-protocol = false
```

### What components are involved in your issue?

Operator, Proxy Agent (Velocity)

### Version

v0.6.0

### Kubernetes Version

v1.28.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
