### ISSUE TITLE
 Pod is invalid: spec.volumes[4].name: Duplicate value: "server-data"

### ISSUE THREAD

**Issue by stevefan1999-personal** [jeremylvln/Shulker#519]
### What happened?

I would like to persist the world, so I added something like this:
```
      podOverrides:
        volumes:
        - emptyDir: {}
          name: server-data
```
But the actual GameServer generated does not take into account of the pod override

### Version

0.8.2

### Kubernetes Version

Irrelevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
