### ISSUE TITLE
Ability to define "external" servers

### ISSUE THREAD

**Issue by jeremylvln** [jeremylvln/Shulker#630]
### Discussed in https://github.com/jeremylvln/Shulker/discussions/615

<div type='discussions-op-text'>

<sup>Originally posted by **ajh123** August 20, 2024</sup>
I have a couple Fabric servers that I would like to add to all my Shulker proxies.
These Fabric servers are not managed by Kubernetes so they would be classed as "external".

This would require two features:
- predefine the proxy's forwarding secret *(so it is known before proxy is made and it can be manually set on the external server)*
- define a list of external servers (see example YAML)

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: public
spec:
  clusterRef:
    name: getting-started
  replicas: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      externalServers:
        - Creative: # <- this would be the name of the server
          address: 1.1.1.1:25565
        - Survival:
          address: 1.1.1.1:25566
```

Currently I would like to migrate my current set up to Shulker which uses Paper for lobbies, a "bear metal" Velocity
, and two Fabric servers. Since I don't need full scalability for these Fabric servers I would like to stick to running these "bear metal" (and Shulker does not support Fabric anyway).</div>
