### ISSUE TITLE
Add TLS support to Redis integration

### ISSUE THREAD

**Issue by jeremylvln** [jeremylvln/Shulker#946]
### Discussed in https://github.com/jeremylvln/Shulker/discussions/912

<div type='discussions-op-text'>

<sup>Originally posted by **kanya-approve** March 19, 2025</sup>
```
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: minecraft-cluster
  namespace: apps
spec:
  networkAdmins:
    - REDACTED
  redis:
    provided:
      credentialsSecretName: redis-credentials
      host: rediss://REDACTED
      port: 6379
    type: Provided
```

I don't think this is working. Does shulker lack support for tls redis?</div>
